#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

if [ $# -eq 0 ]; then
    echo "Usage: babellint <File(s)>"
    exit 255
fi

function fail {
    echo "Failed to lint ${PWD}/$1"
    exit 1
}

for arg in "$@"; do
    trap "fail $arg" ERR
    case "$arg" in
        *.json)
            jq . "$arg" > /dev/null

            reformatted=$(jq . "$arg" -S)
            printf "%s" "$reformatted" > "$arg"
            ;;
        *.yaml)
            ;&
        *.yml)
            yamllint "$arg"
            ;;
        *)
            echo ""
            echo "Error: Don't know how to lint $arg"
            exit 1
            ;;
    esac
done

