#!/bin/bash
set -o errexit
set -o pipefail
set -o nounset

if [ $# -eq 0 ]; then
    echo "Usage: babellint <File(s)>"
    exit 255
fi

function fail {
    echo "Failed to lint ${PWD}/$1"
    exit 1
}

for file in "$@"; do
    # In sparse repositories, some files might be listed but not exist. Skip these.
    if [[ ! -e "$file" ]]; then
        continue
    fi

    trap "fail $file" ERR # VS Code is wrong here, don't use single quotes!

    # Casing should not matter
    pattern=$(echo "$file" | tr '[:upper:]' '[:lower:]')

    case "$pattern" in
        readme.md)
            if [[ -e ".wordlist.txt" ]]; then
                cp ".wordlist.txt" /root/wordlist.txt
            fi

            # Assume that the current folder is a valid proper name
            folder=${PWD##*/}
            echo "$folder" >> /root/wordlist.txt

            pyspelling --config /root/pyspelling-readme-md.yml --name "Readme.md" --source "$file"
            ;& # Yes, fall through please
        *.md)
            markdownlint --fix  "$file"
            ;;
        *.json)
            jq . "$file" > /dev/null

            base=$(jq . "$file")
            reformatted=$(jq . "$file" -S)
            if [[ "$base" != "$reformatted" ]]; then
                printf "%s" "$reformatted" > "$file"
            fi
            ;;
        *.yaml)
            ;&
        *.yml)
            yamllint "$file"
            ;;
        *)
            echo ""
            echo "Error: Don't know how to lint $file"
            exit 1
            ;;
    esac
done

